import {
  ClothingItem,
  OutfitMemory,
  TripPlan,
  StyleInspo,
  UserProfile,
} from "./types";

export const sampleUser: UserProfile = {
  name: "Alex Morgan",
  email: "alex@stylesense.ai",
  avatar: "",
  preferredStyles: ["casual", "minimalist", "streetwear"],
  location: "New York",
  temperatureUnit: "celsius",
  joinDate: "2025-09-15",
};

export const sampleWardrobe: ClothingItem[] = [
  {
    id: "w1",
    name: "White Cotton Tee",
    category: "tops",
    color: "White",
    colorHex: "#FFFFFF",
    season: ["spring", "summer", "all"],
    style: ["casual", "minimalist"],
    imageUrl: "/items/white-tee.jpg",
    warmthLevel: 1,
    waterproof: false,
    dateAdded: "2025-09-15",
    wearCount: 24,
    favorite: true,
  },
  {
    id: "w2",
    name: "Black Slim Jeans",
    category: "bottoms",
    color: "Black",
    colorHex: "#1a1a1a",
    season: ["all"],
    style: ["casual", "minimalist", "streetwear"],
    imageUrl: "/items/black-jeans.jpg",
    warmthLevel: 3,
    waterproof: false,
    dateAdded: "2025-09-15",
    wearCount: 31,
    favorite: true,
  },
  {
    id: "w3",
    name: "Navy Blazer",
    category: "outerwear",
    color: "Navy",
    colorHex: "#1B2A4A",
    season: ["spring", "fall"],
    style: ["formal", "preppy"],
    imageUrl: "/items/navy-blazer.jpg",
    warmthLevel: 3,
    waterproof: false,
    dateAdded: "2025-10-01",
    wearCount: 8,
    favorite: false,
  },
  {
    id: "w4",
    name: "Olive Cargo Pants",
    category: "bottoms",
    color: "Olive",
    colorHex: "#556B2F",
    season: ["spring", "fall"],
    style: ["casual", "streetwear"],
    imageUrl: "/items/cargo-pants.jpg",
    warmthLevel: 3,
    waterproof: false,
    dateAdded: "2025-10-05",
    wearCount: 12,
    favorite: false,
  },
  {
    id: "w5",
    name: "Cream Knit Sweater",
    category: "tops",
    color: "Cream",
    colorHex: "#F5F5DC",
    season: ["fall", "winter"],
    style: ["casual", "minimalist"],
    imageUrl: "/items/cream-sweater.jpg",
    warmthLevel: 4,
    waterproof: false,
    dateAdded: "2025-10-10",
    wearCount: 15,
    favorite: true,
  },
  {
    id: "w6",
    name: "Rain Jacket",
    category: "outerwear",
    color: "Black",
    colorHex: "#2C2C2C",
    season: ["spring", "fall"],
    style: ["casual", "athletic"],
    imageUrl: "/items/rain-jacket.jpg",
    warmthLevel: 3,
    waterproof: true,
    dateAdded: "2025-09-20",
    wearCount: 6,
    favorite: false,
  },
  {
    id: "w7",
    name: "White Sneakers",
    category: "shoes",
    color: "White",
    colorHex: "#F8F8F8",
    season: ["spring", "summer", "fall"],
    style: ["casual", "minimalist", "streetwear"],
    imageUrl: "/items/white-sneakers.jpg",
    warmthLevel: 1,
    waterproof: false,
    dateAdded: "2025-09-15",
    wearCount: 28,
    favorite: true,
  },
  {
    id: "w8",
    name: "Leather Chelsea Boots",
    category: "shoes",
    color: "Brown",
    colorHex: "#5C3317",
    season: ["fall", "winter"],
    style: ["casual", "formal", "vintage"],
    imageUrl: "/items/chelsea-boots.jpg",
    warmthLevel: 3,
    waterproof: true,
    dateAdded: "2025-10-12",
    wearCount: 10,
    favorite: true,
  },
  {
    id: "w9",
    name: "Striped Button-Down",
    category: "tops",
    color: "Blue",
    colorHex: "#4A90D9",
    season: ["spring", "summer", "fall"],
    style: ["casual", "preppy"],
    imageUrl: "/items/striped-shirt.jpg",
    warmthLevel: 2,
    waterproof: false,
    dateAdded: "2025-09-18",
    wearCount: 14,
    favorite: false,
  },
  {
    id: "w10",
    name: "Down Puffer Jacket",
    category: "outerwear",
    color: "Black",
    colorHex: "#111111",
    season: ["winter"],
    style: ["casual", "streetwear"],
    imageUrl: "/items/puffer-jacket.jpg",
    warmthLevel: 5,
    waterproof: true,
    dateAdded: "2025-11-01",
    wearCount: 18,
    favorite: false,
  },
  {
    id: "w11",
    name: "Beige Chinos",
    category: "bottoms",
    color: "Beige",
    colorHex: "#D2B48C",
    season: ["spring", "summer", "fall"],
    style: ["casual", "preppy", "minimalist"],
    imageUrl: "/items/beige-chinos.jpg",
    warmthLevel: 2,
    waterproof: false,
    dateAdded: "2025-09-22",
    wearCount: 19,
    favorite: false,
  },
  {
    id: "w12",
    name: "Grey Hoodie",
    category: "tops",
    color: "Grey",
    colorHex: "#808080",
    season: ["fall", "winter"],
    style: ["casual", "streetwear", "athletic"],
    imageUrl: "/items/grey-hoodie.jpg",
    warmthLevel: 4,
    waterproof: false,
    dateAdded: "2025-10-15",
    wearCount: 22,
    favorite: true,
  },
  {
    id: "w13",
    name: "Floral Summer Dress",
    category: "dresses",
    color: "Multi",
    colorHex: "#FF69B4",
    season: ["spring", "summer"],
    style: ["bohemian", "casual"],
    imageUrl: "/items/floral-dress.jpg",
    warmthLevel: 1,
    waterproof: false,
    dateAdded: "2025-09-25",
    wearCount: 7,
    favorite: false,
  },
  {
    id: "w14",
    name: "Canvas Tote Bag",
    category: "accessories",
    color: "Natural",
    colorHex: "#E8DCC8",
    season: ["all"],
    style: ["casual", "minimalist", "bohemian"],
    imageUrl: "/items/tote-bag.jpg",
    warmthLevel: 1,
    waterproof: false,
    dateAdded: "2025-10-02",
    wearCount: 16,
    favorite: false,
  },
  {
    id: "w15",
    name: "Black Dress Shoes",
    category: "shoes",
    color: "Black",
    colorHex: "#0A0A0A",
    season: ["all"],
    style: ["formal", "elegant"],
    imageUrl: "/items/dress-shoes.jpg",
    warmthLevel: 2,
    waterproof: false,
    dateAdded: "2025-10-20",
    wearCount: 5,
    favorite: false,
  },
  {
    id: "w16",
    name: "Denim Jacket",
    category: "outerwear",
    color: "Blue",
    colorHex: "#4169E1",
    season: ["spring", "fall"],
    style: ["casual", "streetwear", "vintage"],
    imageUrl: "/items/denim-jacket.jpg",
    warmthLevel: 3,
    waterproof: false,
    dateAdded: "2025-09-28",
    wearCount: 11,
    favorite: true,
  },
];

export const sampleMemories: OutfitMemory[] = [
  {
    id: "m1",
    outfit: {
      id: "o1",
      name: "Tokyo Street Style",
      items: ["w1", "w2", "w7", "w16"],
      style: ["casual", "streetwear"],
      occasion: "Sightseeing",
    },
    location: "Tokyo, Japan",
    locationCoords: { lat: 35.6762, lng: 139.6503 },
    weather: {
      temp: 22,
      feelsLike: 21,
      condition: "sunny",
      description: "Clear sky",
      humidity: 55,
      windSpeed: 8,
      icon: "01d",
      high: 25,
      low: 18,
    },
    date: "2025-10-15",
    mood: "adventurous",
    notes: "Perfect outfit for walking around Shibuya",
  },
  {
    id: "m2",
    outfit: {
      id: "o2",
      name: "Rainy London Day",
      items: ["w5", "w2", "w8", "w6"],
      style: ["casual", "minimalist"],
      occasion: "Exploring",
    },
    location: "London, UK",
    locationCoords: { lat: 51.5074, lng: -0.1278 },
    weather: {
      temp: 12,
      feelsLike: 9,
      condition: "rainy",
      description: "Light rain",
      humidity: 82,
      windSpeed: 15,
      icon: "09d",
      high: 14,
      low: 8,
    },
    date: "2025-11-03",
    mood: "cozy",
    notes: "Layered up, stayed warm and dry",
  },
  {
    id: "m3",
    outfit: {
      id: "o3",
      name: "Paris Evening",
      items: ["w9", "w11", "w3", "w8"],
      style: ["preppy", "formal"],
      occasion: "Dinner",
    },
    location: "Paris, France",
    locationCoords: { lat: 48.8566, lng: 2.3522 },
    weather: {
      temp: 16,
      feelsLike: 14,
      condition: "cloudy",
      description: "Overcast",
      humidity: 65,
      windSpeed: 10,
      icon: "04d",
      high: 18,
      low: 12,
    },
    date: "2025-10-28",
    mood: "elegant",
    notes: "Dinner at a bistro near the Seine",
  },
  {
    id: "m4",
    outfit: {
      id: "o4",
      name: "NYC Winter Walk",
      items: ["w12", "w2", "w10", "w8"],
      style: ["casual", "streetwear"],
      occasion: "City Walk",
    },
    location: "New York, USA",
    locationCoords: { lat: 40.7128, lng: -74.006 },
    weather: {
      temp: 2,
      feelsLike: -3,
      condition: "snowy",
      description: "Light snow",
      humidity: 75,
      windSpeed: 20,
      icon: "13d",
      high: 4,
      low: -1,
    },
    date: "2025-12-20",
    mood: "festive",
    notes: "Holiday shopping in Manhattan",
  },
  {
    id: "m5",
    outfit: {
      id: "o5",
      name: "Barcelona Beach Day",
      items: ["w1", "w11", "w7", "w14"],
      style: ["casual", "minimalist"],
      occasion: "Beach",
    },
    location: "Barcelona, Spain",
    locationCoords: { lat: 41.3874, lng: 2.1686 },
    weather: {
      temp: 28,
      feelsLike: 30,
      condition: "sunny",
      description: "Clear sky",
      humidity: 45,
      windSpeed: 5,
      icon: "01d",
      high: 31,
      low: 22,
    },
    date: "2025-08-10",
    mood: "relaxed",
    notes: "La Barceloneta was amazing",
  },
];

export const sampleTrips: TripPlan[] = [
  {
    id: "t1",
    destination: "Milan, Italy",
    startDate: "2026-04-10",
    endDate: "2026-04-14",
    status: "planning",
    packingList: ["w1", "w9", "w2", "w11", "w3", "w7", "w8", "w14"],
    dailyOutfits: [
      {
        date: "2026-04-10",
        weather: {
          temp: 18,
          feelsLike: 17,
          condition: "sunny",
          description: "Clear",
          humidity: 50,
          windSpeed: 8,
          icon: "01d",
          high: 21,
          low: 12,
        },
        dayOutfit: {
          id: "to1",
          name: "Arrival Day",
          items: ["w1", "w11", "w7"],
          style: ["casual", "minimalist"],
        },
      },
      {
        date: "2026-04-11",
        weather: {
          temp: 16,
          feelsLike: 14,
          condition: "cloudy",
          description: "Partly cloudy",
          humidity: 60,
          windSpeed: 12,
          icon: "02d",
          high: 19,
          low: 11,
        },
        dayOutfit: {
          id: "to2",
          name: "Museum Day",
          items: ["w9", "w2", "w3", "w8"],
          style: ["preppy", "formal"],
        },
      },
      {
        date: "2026-04-12",
        weather: {
          temp: 20,
          feelsLike: 19,
          condition: "sunny",
          description: "Sunny",
          humidity: 45,
          windSpeed: 6,
          icon: "01d",
          high: 23,
          low: 14,
        },
        dayOutfit: {
          id: "to3",
          name: "Shopping Day",
          items: ["w1", "w4", "w16", "w7"],
          style: ["casual", "streetwear"],
        },
      },
      {
        date: "2026-04-13",
        weather: {
          temp: 15,
          feelsLike: 13,
          condition: "rainy",
          description: "Rain showers",
          humidity: 75,
          windSpeed: 15,
          icon: "09d",
          high: 17,
          low: 10,
        },
        dayOutfit: {
          id: "to4",
          name: "Rainy Exploration",
          items: ["w5", "w2", "w6", "w8"],
          style: ["casual", "minimalist"],
        },
      },
    ],
  },
];

export const sampleInspirations: StyleInspo[] = [
  {
    id: "s1",
    name: "Minimalist Chic",
    imageUrl: "/inspo/minimalist.jpg",
    tags: ["minimalist", "elegant"],
    matchScore: 87,
    matchedItems: ["w1", "w2", "w7"],
  },
  {
    id: "s2",
    name: "Urban Streetwear",
    imageUrl: "/inspo/streetwear.jpg",
    tags: ["streetwear", "casual"],
    matchScore: 74,
    matchedItems: ["w12", "w4", "w7", "w16"],
  },
  {
    id: "s3",
    name: "Smart Casual",
    imageUrl: "/inspo/smart-casual.jpg",
    tags: ["casual", "preppy"],
    matchScore: 82,
    matchedItems: ["w9", "w11", "w8"],
  },
  {
    id: "s4",
    name: "Boho Summer",
    imageUrl: "/inspo/boho.jpg",
    tags: ["bohemian", "casual"],
    matchScore: 45,
    matchedItems: ["w13", "w14", "w7"],
  },
  {
    id: "s5",
    name: "Classic Formal",
    imageUrl: "/inspo/formal.jpg",
    tags: ["formal", "elegant"],
    matchScore: 65,
    matchedItems: ["w3", "w2", "w15"],
  },
  {
    id: "s6",
    name: "Vintage Vibes",
    imageUrl: "/inspo/vintage.jpg",
    tags: ["vintage", "casual"],
    matchScore: 58,
    matchedItems: ["w16", "w2", "w8"],
  },
];
